# Generated by Django 3.2.14 on 2022-07-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtime',
            name='check_date',
        ),
        migrations.RemoveField(
            model_name='bookingtime',
            name='check_time',
        ),
        migrations.AddField(
            model_name='bookingtime',
            name='check_date_time',
            field=models.DateTimeField(null=True, unique=True),
        ),
    ]
