# Generated by Django 3.2.14 on 2022-07-29 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_bookingtime_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingtime',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookingtime',
            name='car_reg_number',
            field=models.CharField(default=True, max_length=6, primary_key=True, serialize=False),
        ),
    ]
