# Generated by Django 3.2.14 on 2022-07-31 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20220729_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='car_reg_number',
            field=models.CharField(default='XXX-XXX', max_length=6, primary_key=True, serialize=False),
        ),
    ]
