# Generated by Django 3.2.14 on 2022-07-31 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_bookingtime_car_reg_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookingtime',
            name='car_reg_number',
            field=models.CharField(default='XXX-XXX', max_length=7, primary_key=True, serialize=False),
        ),
    ]
